RUN git clone --depth 1 https://github.com/junegunn/fzf.git /home/worktree_docker/.fzf && \
    chown -R worktree_docker:worktree_docker /home/worktree_docker/.fzf && \
    /home/worktree_docker/.fzf/install --all